name:                excalibur-data
version:             1.1.0.2
github:              "githubuser/excalibur-data"
license:             BSD3
author:              "Charles Shuller"
maintainer:          "example@example.com"
copyright:           "2019 Charles Shuller"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/excalibur-data#readme>

dependencies:
  - base >= 4.7 && < 5
  - uuid >= 1.3.13 && < 2
  - time >= 1.8.0.2 && < 2
  - aeson >= 1.3.1.1 && < 2

library:
  source-dirs: src

tests:
  lc-dal-test:
    defaults: hspec/hspec@master
    dependencies:
      - excalibur-data
